#!/usr/bin/env bash
# This Program makes you chat with any one who joins this server.
# Abdisa Dev

echo "
████████╗███████╗██████╗ ███╗   ███╗       ██████╗██╗  ██╗ █████╗ ████████╗
╚══██╔══╝██╔════╝██╔══██╗████╗ ████║      ██╔════╝██║  ██║██╔══██╗╚══██╔══╝
   ██║   █████╗  ██████╔╝██╔████╔██║█████╗██║     ███████║███████║   ██║   
   ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║╚════╝██║     ██╔══██║██╔══██║   ██║   
   ██║   ███████╗██║  ██║██║ ╚═╝ ██║      ╚██████╗██║  ██║██║  ██║   ██║   
   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝       ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝                                                                       
"

red='\033[1;31m'
green='\033[1;32m'
yellow='\033[0;33m'
blue='\033[7;35m'
reset='\033[0m'

while true
do
    echo -e "${green}0. Start Chat${reset}"
    echo -e "${red}1. Exit \n${reset}"

    echo -en "${blue}Enter Your Choice Here:${reset} "
    read Input
    echo

    if [ "$Input" -eq 0 ]; then
        echo -en "${blue}Enter Your Name:${reset} "
        read Name
        echo

    fi
    case "$Input" in
        0) 
            echo -e "Hey ${yellow}$Name${reset} Please Be Patient Until We Establish The Connection . . .\n"
            # Temporary TCP Socket
            exec nc 0.tcp.eu.ngrok.io -q 5 16648
        ;;
        1)
            echo -e "${yellow}-> Bye :(\n${reset}"
            break
        ;;
        *) 
            echo -e "${red}-> Bad Input, Please Try Again!\n${reset}"
        ;;
    esac
done